# # Baremetal Ingress
# releaseStage: staging
# ingress:
#   enabled: true
#   className: nginx
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     cert-manager.io/cluster-issuer: letsencrypt-baremetal


#   labels:
#     app: "staging-templateowner"

#   hosts:
#     - host: stag-templateowner.crytera.com
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: "templateowner"
#             port:
#               name: http

#   tls:
#   - hosts:
#     - stag-templateowner.crytera.com
#     secretName: letsencrypt-nginx-templateowner
############################################################################################################################
# AWS Load Balancer
releaseStage: staging

env:
  SPRING_PROFILES_ACTIVE: "staging"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
          - t3.2xlarge
          - t3.xlarge
          - t3.large

# ############################################################################################################################
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: "shared-ext-ip"
    # alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/scheme: internet-facing # External/Public IP
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: "sg-xxxxxxxx"
    alb.ingress.kubernetes.io/listen-ports:  '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/group: templateowner-ingress
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:xxxxxx:xxxxxxxx:certificate/xxxxxxxx"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: "/hello"
    alb.ingress.kubernetes.io/success-codes: "200"

  labels:
    app: "templateowner"

  hosts:
    - host: stag-templateowner.crytera.com
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "templateowner"
            port:
              name: http

  tls: []
# # ############################################################################################################################
